name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - PumpkinKnightStudio
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      description: You may leave this blank, If you do not know.
      value: "It should not...!"
    validations:
      required: false
  - type: dropdown
    id: minecraftversionverify
    attributes:
      label: Are you playing Vanilla or Modded Minecraft?
      multiple: false
      options:
        - Vanilla
        - Modded    
    validations:
      required: true
  - type: dropdown
    id: minecraftversion
    attributes:
      label: What Minecraft version are you seeing the problem on?
      multiple: false
      options:
        - Vanilla 1.20
        - Vanilla 1.19.4
        - Modded 1.19.4  
  - type: dropdown
    id: mapversion
    attributes:
      label: Map Version
      description: What Map version of our software are you running?
      options:
        - Latest Beta 1.0
        - Alpha 007
        - Alpha 006
        - Alpha 005
        - Alpha 004
        - Alpha 003
        - Alpha 002
        - Alpha 001
    validations:
      required: true
